name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        goos: [linux, darwin]
        goarch: [amd64, arm64]
        exclude:
          - os: ubuntu-latest
            goos: darwin
          - os: macos-latest
            goos: linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Set up environment variables
        run: |
          echo "GOOS=${{ matrix.goos }}" >> $GITHUB_ENV
          echo "GOARCH=${{ matrix.goarch }}" >> $GITHUB_ENV

      - name: Build binary
        run: |
          mkdir -p dist
          go build -o dist/flint-${{ matrix.goos }}-${{ matrix.goarch }} ./main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: flint-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/flint-${{ matrix.goos }}-${{ matrix.goarch }}

  changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.changelog.outputs.changelog }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Generate changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Create Release
    needs: [build, changelog]
    runs-on: ubuntu-latest
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v5
        with:
          path: dist

      - name: Display structure of dist
        run: ls -R dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ needs.changelog.outputs.changelog }}
          files: |
            dist/flint-linux-amd64/flint-linux-amd64
            dist/flint-linux-arm64/flint-linux-arm64
            dist/flint-darwin-amd64/flint-darwin-amd64
            dist/flint-darwin-arm64/flint-darwin-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
